### PR TITLE
Add RSS feed

### PR DESCRIPTION
**Pull request by amazingrando**
**This PR does the following:**
- Adds an RSS feed to the site
- Adds a link to the RSS feed in the footer

### Functional Testing:
- [x] Run `yarn build` (RSS feeds are _not_ created during dev)
- [x] Visit `./public/rss.xml` and verify it is a valid RSS feed of the Emulsify blog posts.
- [x] Run `yarn develop`
- [x] Verify there is a link in the footer that says "RSS Feed," which links to the RSS file for the blog.

### CODE REVIEW

**Comment by laura-johnson** [comment]
@amazingrando I ran **yarn build**, and I was unsure how to serve that so I ran **gatsby serve** to view the rss feed, which I see at localhost:9000/rss.xml and it looks good. However I don't see a link to the rss feed in the footer when I run **yarn develop** or **yarn build**.

**Comment by amazingrando** [comment]
@laura-johnson I just pushed up the code to add the link to the footer. Apparently, it failed to push the last time I did it.

Please review again. Thanks!

**Comment by ryanhagerty** [comment]
@amazingrando LGTM - tests pass and it builds the RSS file. 

Couple things I noticed: 
* The link is hardcoded to `https://www.emulsify.info/rss.xml` rather than going to `localhost` so I had to verify that manually. Not sure if you want to change.
* Also noticed the link is missing on the `404` page.

**Comment by amazingrando** [comment]
@ryanhagerty Thank you for reviewing this. I've updated the link in the footer. The sitemap doesn't show on the 404 page because it technically isn't a page as Gatsby knows it. 

I'm going to merge. TY!

**Pull request merged**
